### ISSUE TITLE
duration is not being respected

### ISSUE THREAD

**Issue by pallaviOE** [jmsanpascual/angular-desktop-notification#3]
I set the duration value to 120 and it still makes the notification disappear after 10-15 seconds.
.config(function (desktopNotificationProvider) {
  desktopNotificationProvider.config({
    autoClose: false,
    showOnPageHidden: true,
    duration:120
   });
  })

**Comment by jmsanpascual** [comment]
@pallaviOE As of now I think that's the default behavior according to this [HTML5 Desktop Notification](https://bugzilla.mozilla.org/show_bug.cgi?id=782211#c118) but I'll try to look for a work around and implement it.

**Comment by jmsanpascual** [comment]
As of now a work around for showing the notification permanently or at long duration is not available, closing this at the moment. I'll also update the document about this.
