### ISSUE TITLE
require() breaking with dist folder

### ISSUE THREAD

**Issue by jastend** [jmsanpascual/angular-desktop-notification#4]
Hi,

Now that the important javascript files are in a dist folder, the package.json needs to be adjusted to allow require() to work.

Here's the updated package.json which should work: https://gist.github.com/jastend/f65b312321c5826e55c1f78af39c9abc

Changes:

Added files array:

```
  "files": ["dist"],
```

Changed path for main:

```
  "main": "dist/angular-desktop-notification.js",
```

Please double check my changes, as I haven't personally created npm packages yet. At least locally, these changes fixed the require() problem for me.

**Comment by jmsanpascual** [comment]
Thank you for filing an issue. This is fixed by @DominikPalo #5.
